load("//:defs.bzl", "package_metadata", "license")

package_metadata(
    name = "package_metadata",
    purl = "pkg:github/bazel-contrib/supply-chain@HEAD",
    attributes = [
        ":license",
    ],
)

license(
    name = "license",
    full_name = "Apache License 2.0",
    spdx_short_identifier = "Apache-2.0",
    urls = [
        "https://github.com/bazel-contrib/supply-chain/blob/main/metadata/LICENSE",
        "https://www.apache.org/licenses/LICENSE-2.0.html",
        "https://spdx.org/licenses/Apache-2.0.html",
    ],
    text = "LICENSE",
)