load("//licenses/rules:license.bzl", "license")
load("//rules:package_metadata.bzl", "package_metadata")

package_metadata(
    name = "package_metadata",
    attributes = [
        ":license",
    ],
    purl = "pkg:github/bazel-contrib/supply-chain@HEAD",
)

license(
    name = "license",
)
