exports_files(
    [
        "purl.bzl",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "srcs",
    srcs = [
        "purl.bzl",
    ] + [
        "@purl.bzl//:srcs",
    ],
    visibility = ["//visibility:public"],
)
