exports_files(
    [
        "license_kind.bzl",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "srcs",
    srcs = [
        "license_kind.bzl",
    ] + [
        "//licenses/providers:srcs",
    ],
    visibility = ["//visibility:public"],
)
