load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "go_license_resolver_lib",
    srcs = ["main.go"],
    importpath = "github.com/bazel-contrib/supply-chain/lib/supplychain-go/cmd/go_license_resolver",
    visibility = ["//visibility:private"],
    deps = [
        "//coverage",
        "//go_bazel",
        "//license_resolver",
    ],
)

go_binary(
    name = "go_license_resolver",
    embed = [":go_license_resolver_lib"],
    visibility = ["//visibility:public"],
)
