exports_files(
    [
        "common.bzl",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "srcs",
    srcs = [
        "common.bzl",
    ] + [
        "//common/private:srcs",
    ],
    visibility = ["//visibility:public"],
)
