exports_files(
    [
        "normalization.bzl",
    ],
    visibility = [
        "//purl/private:__pkg__",
    ],
)

filegroup(
    name = "srcs",
    srcs = [
        "normalization.bzl",
    ],
    visibility = [
        "//purl/private:__pkg__",
    ],
)
