exports_files(
    [
        "alpm.bzl",
        "hackage.bzl",
        "normalization.bzl",
        "pub.bzl",
        "pypi.bzl",
    ],
    visibility = [
        "//purl/private:__pkg__",
    ],
)

filegroup(
    name = "srcs",
    srcs = [
        "alpm.bzl",
        "hackage.bzl",
        "normalization.bzl",
        "pub.bzl",
        "pypi.bzl",
    ],
    visibility = [
        "//purl/private:__pkg__",
    ],
)
