exports_files(
    [
        "copyright_notice.bzl",
        "cpe.bzl",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "srcs",
    srcs = [
        "copyright_notice.bzl",
        "cpe.bzl",
    ],
    visibility = ["//visibility:public"],
)
