load("//private/purl:percent_encoding_test.bzl", "percent_encoding_test")
load("//private/purl:tables.bzl", "percent_encoding")

percent_encoding_test(
    name = "percent_encoding_test",
    cases = percent_encoding.tests,
)
