exports_files(
    [
        "create_package_metadata.bzl",
    ],
    visibility = [
        "//common:__subpackages__",
    ],
)

filegroup(
    name = "srcs",
    srcs = [
        "create_package_metadata.bzl",
    ] + [
        "//providers:srcs",
    ],
    visibility = [
        "//common:__subpackages__",
    ],
)
