exports_files(
    [
        "create_package_metadata.bzl",
        "create_target_info.bzl",
    ],
    visibility = [
        "//common:__subpackages__",
    ],
)

filegroup(
    name = "srcs",
    srcs = [
        "create_package_metadata.bzl",
        "create_target_info.bzl",
    ],
    visibility = [
        "//common:__subpackages__",
    ],
)
