#!/usr/bin/env python3

"""Tool for updating the tables for PURL."""

import argparse
import json
import os
import sys

from typing import List


def _print(f, value):
    if type(value) == list:
        f.write("[\n")
        for element in value:
            _print(f, element)
            f.write(",")
        f.write("]\n")
    elif type(value) == dict:
        f.write("{\n")
        for k, v in value.items():
            f.write(f'"{k}": ')
            _print(f, v)
            f.write(",")
        f.write("}\n")
    elif type(value) == str:
        f.write(f'"{value}"\n')
    elif type(value) == bool:
        if value:
            f.write("True\n")
        else:
            f.write("False\n")
    elif value is None:
        f.write("None\n")
    else:
        print(value)


def _run(args) -> int:
    lc_all = os.environ.get("LC_ALL")
    if lc_all != "en_US.UTF-8":
        print("Your environment settings will reorder the file badly.")
        print("Please rerun as:")
        print('  LC_ALL="en_US.UTF-8"', " ".join(sys.argv))
        return 0

    tests = []
    for root, dirs, files in os.walk(f"{args.spec}/tests"):
        for file in files:
            path = f"{root}/{file}"
            with open(path, "r") as f:
                data = json.load(f)

            tests.extend(data["tests"])

    with open(args.output, "w") as f:
        f.write(
            """# Generated by maintainers/tools/purl_spec_tests/main.py. DO NOT EDIT.
#
# Source: https://github.com/package-url/purl-spec

visibility([
    "//purl/private/tests/...",
])

"""
        )

        f.write(f"tests =")
        _print(f, tests)

    return 0


def main(argv: List[str]) -> int:
    """Main program.
    Args:
      argv: command-line arguments, such as sys.argv (including the program name
      in argv[0]).
    Returns:
      Zero on successful program termination, non-zero otherwise.
    """

    parser = argparse.ArgumentParser(description="Update spec test suite for PURL.")
    parser.add_argument(
        "--spec",
        required=True,
        help="The path to the checkout of https://github.com/package-url/purl-spec",
    )
    parser.add_argument("--output", required=True, help="The .bzl file to write to.")

    return _run(parser.parse_args(argv[1:]))


if __name__ == "__main__":
    sys.exit(main(sys.argv))
