exports_files(
    [
        "package_metadata.bzl",
        "package_metadata_toolchain.bzl",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "srcs",
    srcs = [
        "package_metadata.bzl",
        "package_metadata_toolchain.bzl",
    ] + [
        "//common:srcs",
        "//providers:srcs",
    ],
    visibility = ["//visibility:public"],
)
