load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "label",
    srcs = [
        "label.go",
        "simple.go",
    ],
    importpath = "github.com/bazel-contrib/supply-chain/lib/supplychain-go/label",
    visibility = ["//visibility:public"],
)
