exports_files(
    [
        "package_specification_info.bzl",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "srcs",
    srcs = [
        "package_specification_info.bzl",
    ],
    visibility = ["//visibility:public"],
)
